= Release Instructions

These archetypes should be rebuilt and re-deployed to correspond with each Codename One release.

The process consists of the following steps:

. <<update-cn1-version>>
. <<regenerating-derivative-archetypes>>
. <<updating-the-version>>
. <<push-to-github>>
. <<deploy-to-maven-central>>
. <<_create_new_snapshot_versions>>

[#update-cn1-version]
== Updating the `${cn1.version}` Properties

Archetype projects are basically project templates.  The "template" files that will be included in generated projects are always located inside the `src/main/resources/archetype-resources` directory of an archetype project.  The link:src/main/resources/archetype-resources/[pom.xml file] defines a property named `cn1.version` which dictates which version of Codename One the project will use.  The first thing we need to to is modify this value to point at the new release of Codename One.

We only need update this in the two "root" archetype projects:

. link:cn1lib-archetype/src/main/resources/archetype-resources/pom.xml[cn1lib-archetype] - The archetype for library projects.
. link:cn1app-archetype/src/main/resources/archetype-resources/pom.xml[cn1app-archetype] - The archetype for Application projects.

Open up these two pom.xml files and look for a line like:

[source,xml]
----
<cn1.version>xxx</cn1.version>
----

Where "xxx" is a version number like `7.0.1` or `8.0-SNAPSHOT`.

Change this to the version of Codename One that you want the archetype to use.

[#regenerating-derivative-archetypes]
== Regenerating Derivative Archetypes

This project also contains some archetypes that are derived from the cn1app and cn1lib projects.  These are generated by the archetype-generator sub-module, which uses the templates located in the link:templates[templates directory] to generate full archetype submodules inside the link:generated-archetypes[generated-archetypes directory].

To regenerate these archetypes you need to run the `package` goal with the `generate-archetypes` profile enabled:

[source,bash]
----
mvn package -Pgenerate-archetypes
----

After this is successful, you should see that the "generated-archetypes" directory now contains a number of archetype projects.  Take a look at the `src/main/resurces/archetype-resources/pom.xml` files in those projects to ensure that the `cn1.version` property matches the changes we made in the link:cn1app-archetype[] and the link:cn1lib-archetype[].

[#updating-the-version]
== Updating the Version

Use the https://www.mojohaus.org/versions-maven-plugin/[maven versions plugin] to update the the versions of the project to match the new release of Codename One.  This is different than the `cn1.version` property from the first step.  This step will change the actual versions of the archetype projects themselves for release on Maven central.  It is recommended that you use a version number that matches or corresponds to the Codename One version that you are targeting.  E.g. If the new version of Codename One is 8.0.1, then you would run:

[source,bash]
----
mvn versions:set -DnewVersion=8.0.1
----

If that completes successfully, you must call the `versions:commit` goal to finalize the version change.

[source,bash]
----
mvn versions:commit
----

[#push-to-github]
== Push to Github

At this point it should be ready to deploy to maven central.  Before doing that, let's commit our changes to git and create a tag to mark the version.

[source,bash]
----
git commit -m "Updated to version 8.0.1"
git tag -a v8.0.1 -m "Version 8.0.1"
git push --follow-tags
----

[#deploy-to-maven-central]
== Deploying on Maven Central

=== Deployment Part 1: Deploy to Sonatype Staging Repo

In order for these archetypes to be usable, they need to be deployed to Maven central.  `mvn archetype:generate` only works with archetypes that are on maven central, or installed in your local repository (unless you jump through major hoops), so we really want our archetypes to be on maven central.

If this is the first time you are deploying to maven central with your development machine, you will need to perform some initial configuration of your development environment.  See <<Setting Up Development Environment>> for setup instructions.

If your development environment is already set up, then you can simply run:

[source,bash]
----
bash deploy-to-sonatype.sh
----

TIP: This is just a very thin wrapper script around `mvn`. Check out link:deploy-to-sonatype.sh[the source].

If all goes well, this will deploy the modules to a staging repository on Sonatype.

=== Deployment Part 2: Releasing the Staging Repository

. Log into the https://oss.sonatype.org[Sonatype Nexus Repository Manager].

. Click on the "Staging Repositories" on the left.

. Then scroll down to find the comcodename1... repository and select it.

. Close the repository by pressing the "Close" button in the toolbar at the top of the repository list.
+
This will take a minute while it verifies the repository.  After a couple of minutes, you should press the "Refresh" button on the toolbar.
+
If everything worked, the "Release" button should no longer be grayed out.

. Press the "Release" button.  And wait.  This should finish the release.

NOTE: It will take about 2 hours before the update shows up on Maven Central.

== Create new SNAPSHOT Versions

Now that the release is done, you should change the version number to a SNAPSHOT version for development.  The steps are the same as in <<updating-the-version>> except we'll be changing to a SNAPSHOT version.

e.g.

[source,bash]
----
mvn versions:set -DnewVersion=8.0.2-SNAPSHOT
mvn versions:commit
----

And finally, commit these changes to github.

[source,bash]
----
git commit -m "Updated snapshot version 8.0.2"
git push origin master
----

== Setting Up Development Environment

The following only needs to be performed once.

1. Install Maven if you haven't done this yet.
2. https://issues.sonatype.org/secure/Signup!default.jspa[Sign up for a Sonatype JIRA account]
3. Install gpg if you haven't done this yet, and generate pgp keys to be used for signing the releases.  See <<generating-keys>> for details on generating the keypair.
4. Create a settings.xml file at `~/.m2/settings.xml` if it doesn't exist yet.
3. Add the following to the settings.xml file:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
 <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
   <servers>
     ...
     <server>
      <id>nexus-staging</id>
      <username>YOUR_SONATYPE_USERNAME</username>
      <password>YOUR_SONATYPE_PASSWORD</password>
    </server>
    <server>
      <id>gpg.passphrase</id>
      <passphrase>YOUR_GPG_KEY_PASSPHRASE</passphrase>
    </server>
   </servers>

 </settings>
----

That should do it.  Make sure you replace the `YOUR_SONATYPE_USERNAME`, `YOUR_SONATYPE_PASSWORD`, and `YOUR_GPG_KEY_PASSPHRASE` placeholders with appropriate values.


[#generating-keys]
== Appendix 1: Generating Keypair with gpg

The following is an example readout for generating a keypair with gpg.

[source,bash]
----
C:\Users\Nadeem>gpg --full-gen-key
gpg (GnuPG) 2.1.15; Copyright (C) 2016 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
gpg: keybox 'C:/Users/Nadeem/AppData/Roaming/gnupg/pubring.kbx' created
Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection? 1
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (2048)
Requested keysize is 2048 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0)
Key does not expire at all
Is this correct? (y/N) y
GnuPG needs to construct a user ID to identify your key.
Real name: Nadeem Mohammad
Email address: coolmind182006@gmail.com
Comment:
You selected this USER-ID:
    "Nadeem Mohammad <coolmind182006@gmail.com>"
Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: C:/Users/Nadeem/AppData/Roaming/gnupg/trustdb.gpg: trustdb created
gpg: key 27835B3BD2A2061F marked as ultimately trusted
gpg: directory 'C:/Users/Nadeem/AppData/Roaming/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as 'C:/Users/Nadeem/AppData/Roaming/gnupg/openpgp-revocs.d\5694AA563793429557F1727835B3BD2A223A.rev'
public and secret key created and signed.
pub   rsa2048 2016-08-29 [SC]
      5694AA563793429557F1727835B3BD2A223A
uid                      Nadeem Mohammad <coolmind182006@gmail.com>
sub   rsa2048 2016-08-29 [E]
C:\Users\Nadeem>
----
