name: Build Archetypes

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build cn1app-archetype
      run: mvn -B clean install --file cn1app-archetype/pom.xml -Dcn1Version=7.0.193 -Dcn1PluginVersion=7.0.193

    - name: Build cn1lib-archetype
      run: mvn -B clean install --file cn1lib-archetype/pom.xml -Dcn1Version=7.0.193 -Dcn1PluginVersion=7.0.193