name: Build Archetypes

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Update test properties to use stable Codename One version
      run: |
        find . -name "archetype.properties" -type f -exec sed -i 's/cn1Version=8.0-SNAPSHOT/cn1Version=7.0.193/g' {} +
        find . -name "archetype.properties" -type f -exec sed -i 's/cn1PluginVersion=8.0-SNAPSHOT/cn1PluginVersion=7.0.193/g' {} +

    - name: Build cn1app-archetype
      run: xvfb-run -a mvn -B clean install --file cn1app-archetype/pom.xml

    - name: Build cn1lib-archetype
      run: xvfb-run -a mvn -B clean install --file cn1lib-archetype/pom.xml